# Generated by Django 3.1.7 on 2021-03-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelId', models.CharField(max_length=16)),
                ('roomId', models.CharField(max_length=18)),
                ('orderId', models.CharField(max_length=17)),
                ('NumberOfPeople', models.IntegerField()),
                ('NumberOfRooms', models.IntegerField()),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('NumberOfDays', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('PaidStatus', models.BooleanField()),
                ('TransactionID', models.CharField(max_length=100)),
                ('DatePaid', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
