# Generated by Django 3.1.2 on 2021-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='RoomType',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
